/**
 * SAP GUI (SAP Logon) connection discovery — read-only import source for
 * `adt_create_destination`.
 *
 * Sources, in order:
 *   1. `$ADT_SAPGUI_LANDSCAPE` (path-delimiter separated file list — tests
 *      and exotic setups override discovery)
 *   2. `%APPDATA%\SAP\Common\SAPUILandscape.xml` (SAP GUI 7.50+ for Windows;
 *      `<Include url="file:///...">` entries such as the admin-managed
 *      SAPUILandscapeGlobal.xml are followed)
 *   3. `%APPDATA%\SAP\Common\saplogon.ini` (classic SAP GUI ≤ 7.40 fallback;
 *      conservative field inference, every derived entry is marked)
 *
 * Connection kinds:
 *   - `direct`     — `<Service type="SAPGUI" mode="1" server="host:32nn"/>`;
 *                   ADT URL derived via the SAP port convention
 *                   (HTTPS 443&lt;nn&gt;, HTTP 80&lt;nn&gt; for instance number nn)
 *   - `group`      — load-balancing entry (`msid` + logon group): no single
 *                   application server, so no ADT URL can be derived
 *   - `reference`  — shortcut into a SAPGUI service carrying client / user /
 *                   language (`link` attribute); resolved to its parent
 *
 * The XML is machine-generated by SAP GUI; a small regex tokenizer is enough
 * (and keeps the package dependency-free, matching the protocol package).
 */
import { existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { delimiter, join, resolve } from 'node:path';

/** One connection discovered in the SAP GUI landscape. */
export interface SapGuiConnection {
  uuid: string;
  name: string;
  systemId?: string;
  kind: 'direct' | 'group' | 'reference';
  /** Folder path inside SAP Logon (workspace / node names), when found. */
  folder?: string;
  /** Direct/reference: application server host. */
  host?: string;
  /** Direct/reference: instance number ('00'..'99'). */
  sysnr?: string;
  /** Logon client (reference entries). */
  client?: string;
  /** Stored user (reference entries — SAP GUI keeps it per shortcut). */
  user?: string;
  language?: string;
  /** Reference entries: uuid of the linked SAPGUI service. */
  link?: string;
  /** Saprouter string of the service, when routed (informational). */
  router?: string;
  /** Group entries: logon group + message server host. */
  groupName?: string;
  msHost?: string;
  /** Derived ADT base URL (HTTPS port convention); undefined when not derivable. */
  adtUrl?: string;
  /** Plain-HTTP alternative (ICF on port 80<nn>). */
  httpUrl?: string;
  /** Why no URL, or caveats about the derived one. */
  adtUrlNote?: string;
  /** File the entry was read from. */
  source: string;
}

/** Aggregate discovery result. */
export interface SapGuiLandscape {
  /** Files actually read (absolute paths). */
  sources: string[];
  connections: SapGuiConnection[];
}

/** Attribute map of one XML element. */
type Attrs = Record<string, string>;

function parseAttrs(raw: string): Attrs {
  const attrs: Attrs = {};
  const re = /([\w:-]+)\s*=\s*"([^"]*)"/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(raw)) !== null) attrs[match[1]!] = match[2]!;
  return attrs;
}

/** Extract every `<Tag .../>` element's attributes from machine-generated XML. */
function selfClosingElements(xml: string, tag: string): Attrs[] {
  const out: Attrs[] = [];
  const re = new RegExp(`<${tag}\\b([^>]*?)/>`, 'g');
  let match: RegExpExecArray | null;
  while ((match = re.exec(xml)) !== null) out.push(parseAttrs(match[1]!));
  return out;
}

/** file:/// URL → filesystem path (normalized, Windows-style or POSIX). */
function fileUrlToPath(url: string): string | undefined {
  const match = /^file:\/\/\/(.*)$/.exec(url.trim());
  if (!match) return undefined;
  const rest = decodeURIComponent(match[1]!);
  // Drive-letter form (C:/Users/...) — reattach the slash-less drive colon.
  const raw = /^[A-Za-z]:\//.test(rest) ? rest : `/${rest}`;
  try {
    return resolve(raw);
  } catch {
    return raw;
  }
}

/** Instance number from a DIAG port (3200 -> '00', 3201 -> '01'); undefined otherwise. */
export function sysnrFromDiagPort(port: number | undefined): string | undefined {
  if (port === undefined) return undefined;
  if (port >= 3200 && port <= 3299) return String(port - 3200).padStart(2, '0');
  return undefined;
}

/** host:port splitter for the `server` attribute. */
export function splitServer(server: string): { host: string; port?: number } {
  const bracketed = /^\[(.+)\](?::(\d+))?$/.exec(server); // [v6]:port
  if (bracketed) return { host: bracketed[1]!, port: bracketed[2] ? Number(bracketed[2]) : undefined };
  const colon = server.lastIndexOf(':');
  if (colon > 0 && /^\d+$/.test(server.slice(colon + 1))) {
    return { host: server.slice(0, colon), port: Number(server.slice(colon + 1)) };
  }
  return { host: server };
}

/**
 * Derive ADT URLs from host + instance number: ICF serves /sap/bc/adt on
 * 443<nn> (HTTPS) and 80<nn> (HTTP) on the application server.
 */
export function adtUrlsFor(host: string, sysnr: string | undefined): { adtUrl?: string; httpUrl?: string } {
  if (!sysnr) return { adtUrl: `https://${host}` };
  return { adtUrl: `https://${host}:443${sysnr}`, httpUrl: `http://${host}:80${sysnr}` };
}

/** Map item uuid -> folder path by walking the Workspace/Node tree. */
function itemFolders(xml: string): Map<string, string> {
  const folders = new Map<string, string>();
  const stack: string[] = [];
  const tagRe = /<(\/?)(Workspace|Node|Item)\b([^>]*?)(\/?)>/g;
  let match: RegExpExecArray | null;
  while ((match = tagRe.exec(xml)) !== null) {
    const [, closing, tag, rawAttrs, selfClosing] = match;
    if (tag === 'Workspace' || tag === 'Node') {
      if (closing === '/') {
        // </Node> / </Workspace>: pop this level's name.
        stack.pop();
        continue;
      }
      const attrs = parseAttrs(rawAttrs!);
      stack.push(attrs.name ?? '');
      if (selfClosing === '/') stack.pop();
      continue;
    }
    // Item: always self-closed in the landscape; record the current path
    // keyed by the referenced SERVICE id (what Services/uuid joins against).
    const attrs = parseAttrs(rawAttrs!);
    const serviceId = attrs.serviceid || attrs.uuid;
    if (serviceId) {
      const path = stack.filter((part) => part !== '').join(' / ');
      if (path) folders.set(serviceId, path);
    }
  }
  return folders;
}

/** Parse one SAPUILandscape XML document into connections (refs unresolved). */
function parseLandscapeXml(xml: string, source: string): {
  connections: SapGuiConnection[];
  includes: string[];
} {
  const routers = new Map<string, string>();
  for (const router of selfClosingElements(xml, 'Router')) {
    if (router.uuid) routers.set(router.uuid, router.router ?? router.name ?? '');
  }
  const messageServers = new Map<string, { name?: string; host?: string; port?: string }>();
  for (const ms of selfClosingElements(xml, 'Messageserver')) {
    if (ms.uuid) messageServers.set(ms.uuid, { name: ms.name, host: ms.host, port: ms.port });
  }
  const folders = itemFolders(xml);
  const includes: string[] = [];
  const includeRe = /<Include\b([^>]*?)\/>/g;
  let includeMatch: RegExpExecArray | null;
  while ((includeMatch = includeRe.exec(xml)) !== null) {
    const url = parseAttrs(includeMatch[1]!).url;
    if (url) {
      const includePath = fileUrlToPath(url);
      if (includePath) includes.push(includePath);
    }
  }

  const connections: SapGuiConnection[] = [];
  for (const service of selfClosingElements(xml, 'Service')) {
    if (!service.uuid || !service.name) continue;
    const base = {
      uuid: service.uuid,
      name: service.name,
      systemId: service.systemid || undefined,
      folder: folders.get(service.uuid),
      router: service.routerid ? routers.get(service.routerid) : undefined,
      source,
    };
    if (service.type === 'Reference') {
      connections.push({
        ...base,
        kind: 'reference',
        link: service.link || undefined,
        client: service.client || undefined,
        user: service.user || undefined,
        language: service.language || undefined,
      });
      continue;
    }
    const msid = service.msid || undefined;
    if (msid) {
      // Message-server based entry: `server` holds the logon GROUP name
      // (e.g. PUBLIC), not an application server — no direct ADT URL exists.
      const ms = messageServers.get(msid);
      connections.push({
        ...base,
        kind: 'group',
        groupName: service.server || undefined,
        msHost: ms?.host,
        adtUrlNote:
          'load-balancing (group) connection: no single application server — provide an explicit url ' +
          '(application server or web dispatcher) to create an ADT destination',
      });
      continue;
    }
    const { host, port } = service.server ? splitServer(service.server) : { host: undefined, port: undefined };
    const sysnr = sysnrFromDiagPort(port);
    const { adtUrl, httpUrl } = host ? adtUrlsFor(host, sysnr) : {};
    connections.push({
      ...base,
      kind: 'direct',
      host,
      sysnr,
      adtUrl,
      httpUrl,
      adtUrlNote: host
        ? service.sncname
          ? 'SNC-protected GUI entry — ADT needs a user/password; verify the server allows basic authentication'
          : sysnr
            ? 'URL derived from the GUI app server via the SAP port convention (HTTPS 443<nn>); adjust if a web dispatcher or different port serves /sap/bc/adt'
            : 'server without instance port — URL assumes default HTTPS port; verify'
        : 'entry carries no server host',
    });
  }
  return { connections, includes };
}

/** Candidate landscape files (before existence checks). */
function landscapeCandidates(): string[] {
  const override = process.env.ADT_SAPGUI_LANDSCAPE;
  if (override) return override.split(delimiter).filter((p) => p.length > 0);

  const appData = process.env.APPDATA || join(homedir(), 'AppData', 'Roaming');
  const common = join(appData, 'SAP', 'Common');
  const files = [join(common, 'SAPUILandscape.xml')];
  // Admin-managed global landscape stands alone when the user file is absent.
  const global = join(common, 'SAPUILandscapeGlobal.xml');
  if (!existsSync(files[0]!) && existsSync(global)) files.push(global);
  return files;
}

/**
 * Discover and parse the SAP GUI landscape. Unresolvable files are skipped
 * silently (discovery must degrade to "no GUI found"); parse ERRORS in a file
 * that exists surface as a note on the result instead of throwing, so one
 * broken backup file cannot break discovery.
 */
export function discoverSapGuiLandscape(): SapGuiLandscape {
  const sources: string[] = [];
  const connections: SapGuiConnection[] = [];
  const queue = landscapeCandidates();
  const seen = new Set<string>();
  while (queue.length > 0 && sources.length < 8) {
    const path = queue.shift()!;
    if (seen.has(path)) continue;
    seen.add(path);
    if (!existsSync(path)) continue;
    let xml: string;
    try {
      xml = readFileSync(path, 'utf8');
    } catch {
      continue;
    }
    sources.push(path);
    const parsed = parseLandscapeXml(xml, path);
    connections.push(...parsed.connections);
    queue.push(...parsed.includes);
  }
  resolveReferences(connections);
  appendClassicIni(connections, sources);
  return { sources, connections };
}

/**
 * Resolve `reference` entries to their linked SAPGUI service: the parent's
 * host/sysnr/adtUrl are copied so every reference is independently usable.
 */
function resolveReferences(connections: SapGuiConnection[]): void {
  const byUuid = new Map(connections.filter((c) => c.kind !== 'reference').map((c) => [c.uuid, c]));
  for (const ref of connections) {
    if (ref.kind !== 'reference') continue;
    const parent = ref.link ? byUuid.get(ref.link) : undefined;
    if (!parent) {
      ref.adtUrlNote = `linked service not found in the landscape (${ref.link ?? 'no link'})`;
      continue;
    }
    ref.host = parent.host;
    ref.sysnr = parent.sysnr;
    ref.adtUrl = parent.adtUrl;
    ref.httpUrl = parent.httpUrl;
    ref.router = ref.router ?? parent.router;
    if (parent.kind === 'group') {
      ref.adtUrl = undefined;
      ref.httpUrl = undefined;
      ref.adtUrlNote = 'links a load-balancing (group) connection — provide an explicit url for ADT';
    } else if (!ref.adtUrlNote) {
      ref.adtUrlNote = parent.adtUrlNote;
    }
  }
}

/**
 * Classic saplogon.ini fallback (SAP GUI ≤ 7.40). The item layout shifted
 * across releases, so fields are inferred conservatively: name from the first
 * comma field, host from a host[:port] token, instance number from a standalone
 * two-digit field. Entries duplicating an XML entry by name are dropped.
 */
function appendClassicIni(connections: SapGuiConnection[], sources: string[]): void {
  const override = process.env.ADT_SAPGUI_LANDSCAPE;
  const iniPath = override
    ? undefined // explicit override replaces the whole discovery
    : join(process.env.APPDATA || join(homedir(), 'AppData', 'Roaming'), 'SAP', 'Common', 'saplogon.ini');
  if (iniPath === undefined || !existsSync(iniPath)) return;
  let ini: string;
  try {
    ini = readFileSync(iniPath, 'utf8');
  } catch {
    return;
  }
  const section = /\[System\]([\s\S]*?)(?:\n\[|$)/.exec(ini)?.[1];
  if (!section) return;
  const known = new Set(connections.map((c) => c.name.toLowerCase()));
  let index = 0;
  for (const line of section.split('\n')) {
    const item = /^Item\d+=(.*)$/.exec(line.trim())?.[1];
    if (!item) continue;
    index += 1;
    const fields = item.split(',').map((f) => f.trim());
    const name = fields[0];
    if (!name || known.has(name.toLowerCase())) continue;
    const hostPort = fields.find((f) => /^[A-Za-z0-9._-]+:\d{2,5}$/.test(f));
    const bareHost = fields.find((f) => /^(\d{1,3}\.){3}\d{1,3}$|^[A-Za-z][A-Za-z0-9._-]*$/.test(f));
    const sysnrField = fields.find((f) => /^\d{2}$/.test(f));
    let host: string | undefined;
    let port: number | undefined;
    if (hostPort) {
      const split = splitServer(hostPort);
      host = split.host;
      port = split.port;
    } else if (bareHost && bareHost !== name) {
      host = bareHost;
    }
    if (!host) continue;
    const sysnr = sysnrFromDiagPort(port) ?? sysnrField;
    const { adtUrl, httpUrl } = adtUrlsFor(host, sysnr);
    connections.push({
      uuid: `ini:${index}`,
      name,
      kind: 'direct',
      host,
      sysnr,
      adtUrl,
      httpUrl,
      adtUrlNote: 'inferred from classic saplogon.ini — verify host, port and client',
      source: iniPath,
    });
  }
  sources.push(iniPath);
}

/**
 * Case-insensitive search over the landscape. The query is split on
 * whitespace into terms; EVERY term must match at least one field (name,
 * system id, folder, client, stored user, group, message server) — so
 * "impc qas" finds systems whose name/folder mention both. Empty query
 * returns everything.
 */
export function searchSapGuiConnections(
  connections: SapGuiConnection[],
  query?: string,
): SapGuiConnection[] {
  const terms = (query ?? '').toLowerCase().split(/\s+/).filter((term) => term.length > 0);
  if (terms.length === 0) return connections;
  return connections.filter((c) => {
    const fields = [c.name, c.systemId, c.folder, c.client, c.user, c.groupName, c.msHost]
      .filter((field): field is string => typeof field === 'string' && field.length > 0)
      .map((field) => field.toLowerCase());
    return terms.every((term) => fields.some((field) => field.includes(term)));
  });
}
